# Default values for superdentist-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxSurge: 1
replicaCountSwagger: 1

#Authorization reverse proxy details

image:
  repository: gcr.io/superdentist/superdentist-backend
  tag: latest
  pullPolicy: Always
  health: /healthz
  port: 8090

#Authorization reverse proxy details
asp:
  repository: gcr.io/superdentist/superdentist-auth-proxy
  tag: latest
  port: 8080
  pullPolicy: Always
  arg:
    mode: "authz"


sdServiceAccount:
  name: superdentist-backend
  secret: superdentist-backend
  credential:
    dir: /var/run/secrets/superdentist-backend
    file: super-dentist-backend.json

service:
  type: ClusterIP
  port: 80

## Ingress relation values below

apisRegexp: "/api/(v1|documents|settings)/"
swaggerPagesRegexp: "/docs/(sd|documents|settings)/"
uiPagesRegexp: "/(workspace|login|home)$"
cors:
  origins: '^no_origin_allowed$'
  methods: 'GET, POST, DELETE, PATCH, PUT, OPTIONS'
  headers: 'Accept,Authorization,Cache-Control,Content-Type,Keep-Alive,Origin,User-Agent'
routes:
  - route: /api/v1/?(.*)
    service: superdentist-backend
    port: 80
maxBodySizeMb: 100
# TODO add more routes for frontend etc..

