apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "superdentist-backend.name" . }}
  namespace: default
  labels:
    app: {{ template "superdentist-backend.name" . }}
    chart: {{ template "superdentist-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
    openapi.yaml: {{ include "sd.openapi" . | quote }} 
 
