apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "superdentist-backend.fullname" . }}
  labels:
    app: {{ template "superdentist-backend.name" . }}
    chart: {{ template "superdentist-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
  selector:
    matchLabels:
      app: {{ template "superdentist-backend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "superdentist-backend.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        {{ $sdbcred := printf "%s/%s" .Values.sdServiceAccount.credential.dir .Values.sdServiceAccount.credential.file }}
        - name: {{ .Chart.Name }}-asp
          image: "{{ .Values.asp.repository }}:{{ .Values.asp.tag }}"
          imagePullPolicy: {{ .Values.asp.pullPolicy }}
          args: [
            "--port={{ .Values.asp.port }}",
            "--backend=http://127.0.0.1:{{ .Values.image.port }}",
            "--mode={{ .Values.asp.arg.mode }}",
          ]
          volumeMounts:
          - name: superdentist-backend      
            mountPath: {{ .Values.sdServiceAccount.credential.dir | quote }}
            readOnly: true
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ $sdbcred }}
          ports:
            - name: http-server
              containerPort: {{ .Values.asp.port }}
              protocol: TCP
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.image.health }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1      
          volumeMounts:
          - name: superdentist-backend
            mountPath: {{ .Values.sdServiceAccount.credential.dir | quote }}
            readOnly: true
          - name: sd-pg-root
            mountPath: {{ .Values.sdPGRoot.credential.dir | quote }}
            readOnly: true
          - name: sd-pg-client
            mountPath: {{ .Values.sdPGClient.credential.dir | quote }}
            readOnly: true
          - name: sd-pg-key
            mountPath: {{ .Values.sdPGKey.credential.dir | quote }}
            readOnly: true
          env:
          - name: DB_HOST
            value: 127.0.0.1
          - name: DB_NAME
            value: superdentistpg
          - name: DB_USER
            value: sdadmin
          - name: DB_PASSWORD
            value: qlhH4IJMmFC9jxAa
          - name: SSL_MODE
            value: disable
          - name: SSL_ROOT_CA
            value: /var/run/secrets/server-ca-prod.pem
          - name: SSL_KEY
            value: /var/run/secrets/client-key-prod.pem
          - name: SSL_CERT
            value: /var/run/secrets/client-cert-prod.pem
          - name: SD_REFERRAL_PHONE
            value: '+12157745591'
          - name: DS_NAMESPACE
            value: sdprod
          - name: SD_ADMIN_EMAIL_REPLYTO
            value: referrals@mailer.superdentist.io
          - name: SD_BASE_URL
            value: https://superdentist.io
          - name: SD_PATIENT_REF_CONF
            value: d-0cb214d233c0499691bfba7a42689ac7
          - name: SD_SPECIALIZT_REF_CONF
            value: d-e9288c40cc76436db70a32dc4dba6efa
          - name: GD_REFERRAL_COMPLETED
            value: d-5223f0628162417591e27d9810460ebc
          - name: GD_REFERRAL_AUTO
            value: d-cd2ce581f5e14250a914d6a655d93f10
          - name: CLINIC_NOTIFICATION_NEW
            value: d-7ab65eeeb1144af285bc31aa39fb6873
          - name: PATINET_EMAIL_NOTIFICATION
            value: d-c2e691190e1145d58d2fdda9782257ed
          - name: CONTINUE_URL
            value: https://superdentist.io
          - name: PORT
            value: {{ .Values.image.port | quote }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ $sdbcred }}
          - name: GCP_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.sdAPISecret.name}}
                key : {{.Values.sdAPISecret.secret}}
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.sgAPISecret.name}}
                key : {{.Values.sgAPISecret.secret}}
          - name: TWI_SID
            valueFrom:
              secretKeyRef:
                name: {{.Values.twiSIDSecret.name}}
                key : {{.Values.twiSIDSecret.secret}}
          - name: TWI_AUTH
            valueFrom:
              secretKeyRef:
                name: {{.Values.twiAuthSecret.name}}
                key : {{.Values.twiAuthSecret.secret}}
          - name: QR_ENC_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.encqr.name}}
                key : {{.Values.encqr.secret}}
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=superdentist:us-central1:sd-prod-sql=tcp:5432"
            - "-credential_file=/var/run/secrets/superdentist-backend/super-dentist-backend.json"
          volumeMounts:
          - name: superdentist-backend
            mountPath: {{ .Values.sdServiceAccount.credential.dir | quote }}
            readOnly: true
      volumes:
      - name: superdentist-backend
        secret:
          secretName: {{ .Values.sdServiceAccount.secret }}
      - name: sd-pg-root
        secret:
          secretName: {{ .Values.sdPGRoot.secret }}
      - name: sd-pg-client
        secret:
          secretName: {{ .Values.sdPGClient.secret }}
      - name: sd-pg-key
        secret:
          secretName: {{ .Values.sdPGKey.secret }}