apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging-tls
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: puneet@superdentist.io
    privateKeySecretRef:
      name: letsencrypt-staging-tls
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx