apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-production-tls
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: puneet@superdentist.io
    privateKeySecretRef:
      name: letsencrypt-production-tls
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx