apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: puneet@superdentist.io
    privateKeySecretRef:
      name: letsencrypt-staging-dns
    solvers:
    - selector: {}
      dns01:
        clouddns:
          project: superdentist
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: super-dentist-backend.json