apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: superdentist-io-cert
  namespace: default
spec:
  secretName: super-dentist-io-tls
  issuerRef:
    name: letsencrypt-production-dns
  dnsNames:
  - superdentist.io
  - www.superdentist.io